version: "3.0"
services:
    inventory-service:
        image: inventory:latest
        container_name: inventory
        ports:
        - "8081:8081"
        expose:
        - "8081"
        working_dir: /
        command: java -jar inventory.jar
        networks:
        - order-network
        logging:
          driver: "fluentd"
          options:
            fluentd-address: localhost:24224
            tag: testlogging.log 
networks:
    order-network:
         external: true